name: Build and deploy Python project to Azure Function App - wistia-ingestion-lm2

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Zip artifact
        run: zip -r release.zip . --exclude "*.git*"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_782E35AD6DC04C3EAAE9513933EFB5FC }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4326066641284E77829DBD0A59D27BF6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DD2963B537B74BDC96FD5D6E0136961E }}

      - name: Set app settings
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az functionapp config appsettings set \
              --name wistia-ingestion-lm2 \
              --resource-group wistia-analytics \
              --settings WEBSITE_RUN_FROM_PACKAGE=1 ENABLE_ORYX_BUILD=false SCM_DO_BUILD_DURING_DEPLOYMENT=false

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: 'wistia-ingestion-lm2'
          package: 'release.zip'
          scm-do-build-during-deployment: false
          enable-oryx-build: false